version: "3.7"
services:
    db:
        image: postgres:13-alpine
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        container_name: db
        ports: 
            - '5432:5432'
        volumes:
            - ./db/scripts/1_auth_schema.sql:/docker-entrypoint-initdb.d/1_auth_schema.sql
            - ./db/scripts/2_lms_schema.sql:/docker-entrypoint-initdb.d/2_lms_schema.sql

    auth:
        image: yzia2000/zims-auth:latest
        environment:
            - NODE_ENV=production
            - DATABASE_URL=${DATABASE_URL}
            - JWT_SECRET=${JWT_SECRET}
        build:
            context: ./auth
        container_name: auth-api
        depends_on:
            - db
        ports:
            - '5000:5000'

    lms:
        image: yzia2000/zims-lms:latest
        environment:
            - NODE_ENV=production
            - DATABASE_URL=${DATABASE_URL}
            - JWT_SECRET=${JWT_SECRET}
        build:
            context: ./lms
        container_name: lms-api
        depends_on:
            - db
        ports:
            - '5001:5000'
