version: "3.7"
services:
    db:
        image: postgres:13-alpine
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        container_name: db-test
        ports: 
            - '5432:5432'
        volumes:
            - ./db/scripts:/docker-entrypoint-initdb.d

    auth:
        image: yzia2000/zims-auth:test
        environment:
            - NODE_ENV=test
            - DATABASE_URL=${DATABASE_URL}
            - JWT_SECRET=${JWT_SECRET}
        build:
            context: ./auth
            target: builder
        container_name: auth-api-test
        command: ./wait-for-it.sh db:5432 -- /bin/sh -c "npm run test"
        depends_on:
            - db

        ports:
            - '5000:5000'

    lms:
        image: yzia2000/zims-lms:test
        environment:
            - NODE_ENV=test
            - DATABASE_URL=${DATABASE_URL}
            - JWT_SECRET=${JWT_SECRET}
        build:
            context: ./lms
            target: builder
        container_name: lms-api-test
        command: ./wait-for-it.sh db:5432 -- /bin/sh -c "npm run test"
        depends_on:
            - db

        ports:
            - '5001:5000'
