version: "3.7"
services:
    db:
        image: postgres:13-alpine
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=database
        container_name: db
        ports: 
            - '5432:5432'
        volumes:
            - ./db/scripts/*schema.sql:/docker-entrypoint-initdb.d

    auth:
        image: yzia2000/zims-auth:latest
        environment:
            - NODE_ENV=production
        build:
            context: ./auth
        container_name: auth-api
        depends_on:
            - db
        ports:
            - '5000:5000'

    lms:
        image: yzia2000/zims-lms:latest
        environment:
            - NODE_ENV=production
        build:
            context: ./lms
        container_name: lms-api
        depends_on:
            - db
        ports:
            - '5001:5000'
