version: "3.7"
services:
    lmsdb:
        image: postgres:13-alpine
        env_file:
            - .env.local
        container_name: lmsdb-test
        ports: 
            - '5432:5432'
        volumes:
            - ./dbscripts:/docker-entrypoint-initdb.d

    sut:
        image: yzia2000/zims-classroom:test
        env_file:
            - .env.local
        environment:
            - NODE_ENV=test
        build:
            context: .
            target: builder
        container_name: lms-api-test
        command: ./wait-for-it.sh lmsdb:5432 -- /bin/sh -c "npm run test"
        depends_on:
            - lmsdb

        ports:
            - '5000:5000'
